#设置端口
server:
  port: 8888
  servlet:
    session:
      timeout: 180m

#配置数据源的属性
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/layui-cms?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: root
      password: 123456
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,wall
      validationQuery: SELECT 'x'   #验证连接
      enable: true
      #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


#配置mybatisplus
mybatis-plus:
  #xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #数据库类型
      db-type: MYSQL
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
    banner: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true


#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  anon-urls:
    - /index.html*
    - /sys/toLogin*
    - /login/login*
    - /resources/**
  login-url: /index.html
  log-out-url: /login/logout*
  authc-ulrs:
    - /**

#log日志配置
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug